# Generated by Django 3.2.3 on 2021-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('cases', models.IntegerField()),
                ('todayCases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('todayDeaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('todayRecovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('updated', models.IntegerField()),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ipCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
