# Generated by Django 3.2.8 on 2021-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
