# Generated by Django 3.2.8 on 2021-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topcountries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystatistics',
            name='updatedClient',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicdata',
            name='updatedClient',
            field=models.IntegerField(default=0),
        ),
    ]
