# Generated by Django 3.2.8 on 2021-10-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystatistics',
            name='yesterdayData',
            field=models.TextField(null=True),
        ),
    ]
