# Generated by Django 3.2.8 on 2021-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_countrystatistics_yesterdaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('lastUpdated', models.IntegerField()),
            ],
        ),
    ]
